"""Add approved flag to posts

Revision ID: 85505cb4e7cc
Revises: b421308609f9
Create Date: 2025-07-02 23:18:33.813673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85505cb4e7cc'
down_revision = 'b421308609f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
